=== danielmarschall/oidplus/plugins/manifest_plugin.xsd
<?xml version="1.0"?>
<xs:schema targetNamespace="urn:oid:1.3.6.1.4.1.37476.2.5.2.5.2"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="manifest">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="type" minOccurs="1"
					maxOccurs="1" />

				<xs:element name="info" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" minOccurs="1"
								maxOccurs="1" />
							<xs:element type="xs:string" name="author"
								minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:string" name="version"
								minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:string" name="descriptionHTML"
								minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:string" name="oid" minOccurs="1"
								maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="php" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="mainclass"
								minOccurs="1" maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="css" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="file" minOccurs="0"
								maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="js" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="file" minOccurs="0"
								maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielmarschall/oidplus/plugins/publicPages/500_resources/manifest.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<manifest
	xmlns="urn:oid:1.3.6.1.4.1.37476.2.5.2.5.2" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:oid:1.3.6.1.4.1.37476.2.5.2.5.2 https://oidplus.viathinksoft.com/oidplus/plugins/manifest_plugin.xsd">

	<type>OIDplusPagePluginPublic</type>

	<info>
		<name>Resources</name>
		<author>ViaThinkSoft</author>
		<version />
		<descriptionHTML />
		<oid>1.3.6.1.4.1.37476.2.5.2.4.1.500</oid>
	</info>

	<php>
		<mainclass>OIDplusPagePublicResources</mainclass>
	</php>

	<css>
	</css>

	<js>
	</js>
	
</manifest>

=== danielmarschall/oidplus/plugins/objectTypes/doi/manifest.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<manifest
	xmlns="urn:oid:1.3.6.1.4.1.37476.2.5.2.5.2" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:oid:1.3.6.1.4.1.37476.2.5.2.5.2 https://oidplus.viathinksoft.com/oidplus/plugins/manifest_plugin.xsd">

	<type>OIDplusObjectTypePlugin</type>

	<info>
		<name>Digital Object Identifier (DOI)</name>
		<author>ViaThinkSoft</author>
		<version />
		<descriptionHTML />
		<oid>1.3.6.1.4.1.37476.2.5.2.4.8.1</oid>
	</info>

	<php>
		<mainclass>OIDplusObjectTypePluginDoi</mainclass>
	</php>
	
</manifest>
